<!-- Do not edit this file. It is automatically generated by API Documenter. -->

[Home](./index.md) &gt; [@rocketbase/vue-extra-decorators](./vue-extra-decorators.md) &gt; [EmitError](./vue-extra-decorators.emiterror.md)

## EmitError() function

Emits a given vue event after failed execution with the error being the event parameter.

<b>Signature:</b>

```typescript
declare function EmitError(event?: string, rethrow?: boolean): (target: any, key: string, desc: TypedPropertyDescriptor<TFunction<any, unknown[], Vue>>) => void;
```

## Parameters

|  Parameter | Type | Description |
|  --- | --- | --- |
|  event | <code>string</code> | The name of the event to trigger, defaults to <code>error:METHODNAME</code> where METHODNAME is the name of the decorated method. |
|  rethrow | <code>boolean</code> | If the error should be re-thrown after emitting the event |

<b>Returns:</b>

`(target: any, key: string, desc: TypedPropertyDescriptor<TFunction<any, unknown[], Vue>>) => void`

## Remarks

If a promise is returned, it will trigger the event after the promise was rejected. Will never emit on success, use [Emit()](./vue-extra-decorators.emit.md) instead.

## Example


```typescript
@Component({})
export default class FooBar extends Vue {
  @EmitError("save-failure")
  private async saveFooBar() {
    // ... Implementation
    throw new Error("Error trying to save foobar");
  }
}

```
[Emit()](./vue-extra-decorators.emit.md) [EmitError()](./vue-extra-decorators.emiterror.md) 

